# Generated by Django 4.0 on 2024-02-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePost',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=250)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('header_post', models.CharField(max_length=250)),
                ('time_post', models.DateTimeField()),
                ('content', models.TextField()),
                ('num_like', models.IntegerField()),
                ('num_comment', models.IntegerField()),
                ('type_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_service.typepost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_service.post')),
            ],
        ),
    ]
