# Generated by Django 4.0 on 2024-02-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id_pay_slip', models.AutoField(primary_key=True, serialize=False)),
                ('num_day_off', models.IntegerField()),
                ('price', models.FloatField()),
                ('num_work_day', models.IntegerField()),
                ('evaluate', models.CharField(max_length=250)),
                ('note', models.CharField(max_length=250)),
                ('month', models.IntegerField()),
                ('num_late_day', models.IntegerField()),
                ('num_leave_early', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
            ],
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id_workday', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('name_day', models.CharField(max_length=250)),
                ('wage_sum', models.CharField(max_length=250)),
                ('num_hour_work', models.IntegerField()),
                ('status', models.CharField(max_length=250)),
                ('num_errors', models.IntegerField()),
                ('payslip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_service.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticalTimeKeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_statistical', models.IntegerField(default=0)),
                ('num_day_off', models.IntegerField(default=0)),
                ('num_workday', models.IntegerField(default=0)),
                ('num_late_day', models.IntegerField(default=0)),
                ('num_leave_early', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
                ('workdays', models.ManyToManyField(to='time_service.Workday')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('total_wage', models.FloatField()),
                ('time', models.DateTimeField()),
                ('content', models.CharField(max_length=250)),
                ('type_payment', models.CharField(max_length=250)),
                ('payslip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_service.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id_check_out', models.AutoField(primary_key=True, serialize=False)),
                ('time_out', models.TimeField()),
                ('money', models.FloatField()),
                ('status', models.CharField(max_length=250)),
                ('time_difference', models.CharField(max_length=250)),
                ('workday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_service.workday')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id_check_in', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.TimeField()),
                ('money', models.FloatField()),
                ('status', models.CharField(max_length=250)),
                ('time_difference', models.CharField(max_length=250)),
                ('workday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_service.workday')),
            ],
        ),
    ]
