# Generated by Django 4.0 on 2024-02-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPost',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('title_notification', models.CharField(max_length=250)),
                ('body_notification', models.CharField(max_length=250)),
                ('time_notification', models.DateTimeField()),
                ('is_read', models.IntegerField()),
                ('type_notification', models.IntegerField()),
                ('id_data', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user')),
            ],
        ),
    ]
