# Generated by Django 4.0 on 2024-02-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('time_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCalendar',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=250)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id_calendar', models.AutoField(primary_key=True, serialize=False)),
                ('header_calendar', models.CharField(max_length=250)),
                ('body_calendar', models.TextField()),
                ('address', models.CharField(max_length=250)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('type_calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_service.typecalendar')),
                ('work_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_service.workday')),
            ],
        ),
    ]
